### ISSUE TITLE
Suggestion: use MCDR plugin to auto reload instead of NodeChangeWatcher

### ISSUE THREAD

**Issue by spyeic** [DancingSnow0517/MCDR-Command#9]
Instead of creating a new thread to listen to changes in the node.json, maybe using the server command ```mcdrc reload``` in the mcdr plugin is better.

Add this line in function ```new_on_plugin_registry_changed```:
```server.execute('mcdrc reload')```

**Comment by DancingSnow0517** [comment]
finshed see release.
